name: docker_publish

on:
  push:
    branches:
    - 'main'
    - 'dev'
    tags:
    - '*'

jobs:
  lint_test:
    uses: babylonlabs-io/.github/.github/workflows/reusable_go_lint_test.yml@hiep/add-gosec
    secrets: inherit
    with:
      run-unit-tests: true
      run-integration-tests: false
      run-lint: true
      run-build: true

  docker_pipeline:
    uses: babylonlabs-io/.github/.github/workflows/reusable_docker_pipeline.yml@hiep/add-gosec
    needs: ["lint_test"]
    secrets: inherit
    with:
      publish: true
      dockerfile: ./contrib/images/babylond/Dockerfile
      repoName: babylond
